services:
  - type: web
    name: face-recognition-app
    env: python
    plan: free
    python_version: "3.11"  # Set Python version at service level
    envVars:
      # Optional: Add Redis URL if using Redis
      - key: REDIS_URL
        value: "redis://<internal-redis-url>:6379"
    buildCommand: |
      # Update system packages and install dependencies for dlib/face-recognition
      apt-get update && \
      apt-get install -y build-essential cmake && \
      # Upgrade pip
      python -m pip install --upgrade pip && \
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: "gunicorn app:app"  # Make sure your Flask app is in app.py with 'app' instance
