services:
  - type: web
    name: face-recognition-app
    env: python
    plan: free
    buildCommand: |
      # Install system dependencies
      apt-get update && apt-get install -y build-essential cmake libopenblas-dev liblapack-dev
      # Install Python dependencies
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn --worker-class gevent --bind 0.0.0.0:$PORT app:app
