services:
  - type: web
    name: face-recognition-app
    env: python
    plan: free
    python_version: "3.11"  # Use Python 3.11
    envVars:
      # Optional: add Redis URL if your app uses Redis
      - key: REDIS_URL
        value: "redis://<internal-redis-url>:6379"
    buildCommand: |
      # Install system dependencies for dlib and Pillow
      apt-get update && \
      apt-get install -y build-essential cmake libjpeg-dev zlib1g-dev libpng-dev libtiff-dev libwebp-dev libopenjp2-7-dev libfreetype6-dev pkg-config && \
      # Upgrade pip, setuptools, and wheel
      python -m pip install --upgrade pip setuptools wheel && \
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: "gunicorn app:app"  # Ensure app.py has 'app' instance
